# Generated by Django 4.2.7 on 2023-11-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_item_user_data_first_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterField(
            model_name='user_data_first',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
