# Generated by Django 4.2.7 on 2023-11-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_data_first_hse_relation_user_data_first_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data_first',
            name='EduLevel',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='user_data_first',
            name='Facult',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='user_data_first',
            name='Prog',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_data_first',
            name='kurs',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
