# Generated by Django 4.2.7 on 2023-11-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0006_remove_user_data_first_edulevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('profile_pic', models.ImageField(upload_to='profile_pics/')),
                ('your_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('telega', models.CharField(max_length=50, unique=True)),
                ('phone_num', models.CharField(max_length=12)),
                ('O_sebe', models.CharField(max_length=200)),
                ('HSE_relation', models.CharField(default='-', max_length=30)),
                ('kurs', models.CharField(default='-', max_length=20)),
                ('job', models.CharField(default='-', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
