# Generated by Django 4.2.7 on 2023-11-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
