# Generated by Django 4.2.7 on 2023-11-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile_pics/')),
                ('phone_num', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='User_Text_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('telega', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=12)),
                ('O_sebe', models.CharField(max_length=200)),
                ('HSE_relation', models.CharField(default='-', max_length=30)),
                ('kurs', models.CharField(default='-', max_length=50)),
                ('job', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Data_First',
        ),
    ]
