# Generated by Django 4.2.7 on 2023-11-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_user_files_user_text_data_delete_user_data_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_files',
            name='phone_num',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='user_text_data',
            name='phone_num',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
